development:
  adapter: mysql
  database: domaim_development  
  username: root
  password: 
  host: localhost
test:
  adapter: mysql
  database: domaim_test
  username: root
  password: 
  host: localhost
production:
  adapter: mysql
  database: hostee_production
  username: hostee_prod
  password: tu7cw3ba
  host: localhost